arguments:
  app_name: Radarr
  dependencies:
    - curl sqlite3 mediainfo
  docs: https://wiki.servarr.com/Radarr
  homepage: https://github.com/radarr/radarr
  multi-user: true
  ports: 
    - default: [7878-7928]
    - ssl: [9898-9948]
  subdomain: false
  options: 
    - 4k
    - develop|main
usage:
  - command: "omni software add radarr -u [username]"
    note: "Add Radarr for USERNAME"
  - command: "omni software add radarr -u [username] -o [4k]"
    note: "Add Radarr4k for USERNAME"
  - command: "omni software remove radarr -u [username]"
    note: "Remove Radarr for USERNAME"
  - command: "omni software remove radarr -u [username] -o [4k]"
    note: "Remove Radarr4k for USERNAME"
  - command: "omni software reinstall radarr -u [username]"
    note: "Reinstall Radarr for USERNAME"
  - command: "omni software reinstall radarr -u [username] -o [4k]"
    note: "Reinstall Radarr4k for USERNAME"
  - command: "omni software update radarr -u [username]"
    note: "Update Radarr for USERNAME"
  - command: "omni software update radarr -u [username] -o [4k]"  
    note: "Update Radarr4k for USERNAME"
  - command: "omni software backup radarr -u [username]"
    note: "Backup Radarr for USERNAME"
  - command: "omni software backup radarr -u [username] -o [4k]"
    note: "Backup Radarr4k for USERNAME"
