arguments:
  app_name: Plex Debrid
  dependencies: [
    "git",
    "fuse",
    "libfuse-dev",
    "python3",
    "python3-pip",
    "python3-venv",
    "xmlstarlet"
  ]
  docs: https://github.com/itsToggle/plex_debrid/wiki
  homepage: https://github.com/itsToggle/plex_debrid
  multi_user: true
  subdomain: false
  manual_dependencies:
  - name: rclone_rd
    type: binary
    method: wget
    url: https://github.com/itsToggle/rclone_RD/releases/download/v1.58.1-rd.2.2/rclone-linux
  options: #option should be the real debrid api key value
  ports: #none
    #- default: [7878-7928]
    #- ssl: [9898-9948]
  connects_to:
    Plex:
      keys:
        - "plexOnlineToken"
    Overseer:
      keys:
        - "apiKey"
        - "proxy_pass"
    Jackett:
      keys:
        - "proxy_pass"
        - "APIKey"
        - "LocalBindAddress"
    Prowlarr:
      keys:
        - "apiKey"
        - "proxy_pass"
usage:
  - command: "zen software add plex_debrid -u [username]"
    note: "Add Plex Debrid for USERNAME"
  - command: "zen software remove plex_debrid -u [username]"
    note: "Remove Plex Debrid for USERNAME"
  - command: "zen software reinstall plex_debrid -u [username]"
    note: "Reinstall Plex Debrid for USERNAME"
  - command: "zen software update plex_debrid -u [username]"
    note: "Update Plex Debrid for USERNAME"
  - command: "zen software backup plex_debrid -u [username]"
    note: "Backup Plex Debrid for USERNAME"
