name: Create Release and Update scripts

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Git
        id: git-config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y shc gawk make
          git clone --recursive https://github.com/reconquest/shdoc
          cd shdoc
          sudo make install
          cd
      
      - name: Checkout MediaEase/workflows repository
        uses: actions/checkout@v4
        with:
          repository: MediaEase/workflows
          token: ${{ secrets.MEDIAEASE_ACCESS_TOKEN }}
          ref: main
          path: MediaEase-workflows

      - name : Generate documentation
        run: |
          cp MediaEase-workflows/autodoc.sh .
          rm -rf MediaEase-workflows
          chmod +x autodoc.sh
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'scripts/src/.*\.sh' | xargs -I {} ./autodoc.sh {} "external"

      - name: Commit and push changes
        run: |
          git add 
          git commit -m "docs: update documentation" -m "This commit was generated by the autodoc.sh script"
          git push origin ${{ github.ref }}

  create_release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        id: git-config
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Run release script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          DEVELOP_BRANCH: develop
          # PRERELEASE_IDENTIFIER: 'alpha'
          PRERELEASE_REPO: 'MediaEase/MediaEase'
          PRERELEASE_FILE: 'prerelease_identifier.txt'
        run: |
          curl -sSL https://raw.githubusercontent.com/MediaEase/HarmonyUI/develop/.github/scripts/create-release.sh -o .github/scripts/create-release.sh
          chmod +x .github/scripts/create-release.sh
          bash .github/scripts/create-release.sh

  update_submodule:
    runs-on: ubuntu-latest
    needs: create_release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Repository Dispatch for scripts
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: MediaEase/MediaEase
          event-type: scripts-release
          client-payload: '{ "submodule": "scripts", "ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'
